### ISSUE TITLE
About Database File

### ISSUE THREAD

**Issue by SagarJate** [devang29/FACE-RECOGNITION-BASED-ATTENDANCE-MANAGEMENT-SYSTEM#1]
Hi,
   Greeting for the day....!!!
I want database file, Please send me database file following email.
sagar.jate1991@gmail.com

Thanks & Regards,
Sagar Jate

**Comment by devang29** [comment]
Database file is not available as of now Sagar.

**Comment by SagarJate** [comment]
Thank you for positive response.
